paths:
  /api/products:
    get:
        summary: Obtiene los productos
        tags:
          - Products
        responses:
          "200":
            description: Usuarios obtenidos satisfactoriamente